### ISSUE TITLE
Remove Admin UI and drivers from the codebase

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb_rebirth#1]
Each driver should have its own repository under our org.

**Comment by thelinuxlich** [comment]
That demos folder can probably go away too

**Comment by atris** [comment]
Removed the Admin UI folder

**Comment by ChrisTalman** [comment]
Is there a place where the future of the Admin UI is being discussed? I see [rebirth-desktop](https://github.com/RebirthDB/rebirthdb-desktop), is that it?

**Comment by thelinuxlich** [comment]
Yes sir!

**Comment by atris** [comment]
Removed the UI, Driver and Admin folder
