### ISSUE TITLE
Versioning and rebranding

### ISSUE THREAD

**Issue by gabor-boros** [rethinkdb/rethinkdb_rebirth#14]
The beta release still says that the installed db is RethinkDB and v2.3.x.

Do we have plans for rebranding and bumping the version number?

**Comment by floydkots** [comment]
Yes we have plans for rebranding and bumping the version number. I expect we shall formalize the plans soon.

**Comment by gabor-boros** [comment]
Sounds good. We should have a timeline. What do you think?

I think a general timeline where all the required actions are represented (for example driver updates, regression testing, etc) would be reasonable.

**Comment by floydkots** [comment]
Certainly! That will help us progress in a more coordinated and definite way. Looking into organizing a meeting.

**Comment by asakatida** [comment]
Solved by PR #24. Thanks @floydkots.
