### ISSUE TITLE
RebirthDB's packaging fails at the signing stage, missing secret key

### ISSUE THREAD

**Issue by floydkots** [rethinkdb/rethinkdb_rebirth#17]
Since we have no access to RethinkDB's secret key that was used to sign the  `rethinkdb` packages, the packaging fails at the signing stage.

We have already created our pair of PGP keys, and will use these to sign our `rebirthdb` packages. We will also need to rename the packages and change maintainer details.

Finally, to avoid confusion, we will also need to rename the server executable, process names and a couple of error messages, to be relevant to the new package name.

**Comment by gabor-boros** [comment]
Please also note that this issue is blocking the integration tests for drivers. The built package is needed for automated integration testing.

**UPDATE**
@floydkots built a package for integration testing to not block the python development.

**Comment by adallow** [comment]
Question: woudln't "AtnNn" from the rethinkdb open source project (post rethink company shutodwn) have the rethinkdb keys, as he did a new release post the rethinkdb shutdown for version 2.3.6 of rethink db. His details are: 
https://github.com/AtnNn
etienne@atnnn.com

he had also set up a build project  for rethink:
https://github.com/rethinkdb/rethinkdb-nix

**Comment by thelinuxlich** [comment]
We tried contacting everyone for months, they know the fork exists and don't seem eager to help...
