### ISSUE TITLE
Rename to RethonkDB

### ISSUE THREAD

**Issue by MicroDroid** [rethinkdb/rethinkdb_rebirth#26]

**Comment by atris** [comment]
Spam issue?

**Comment by MicroDroid** [comment]
Not really, it's just a better name. Rebirth is hard to pronounce.

**Comment by SilverCory** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/5b384c45-69d3-4dcf-b0c3-0d86b1b944fb-5ca02949-be7d-4a3e-bee7-6d4e10770b66-v1.png?transparent=1&palette=1&width=246)

**Comment by MicroDroid** [comment]
I wasn't even kidding about this (I don't usually meme through GitHub)

But, ok. :+1:

**Comment by SilverCory** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/204d8f0d-50e5-4db5-a810-f6525a68dc39-5ca02949-be7d-4a3e-bee7-6d4e10770b66-v1.png?transparent=1&palette=1&width=246)

**Comment by schnapster** [comment]
![image](https://user-images.githubusercontent.com/6048348/44046060-abcc8008-9f2a-11e8-800b-821955622250.png)
