### ISSUE TITLE
We need a Milestone/Roadmap

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb_rebirth#27]
I'm **very** excited that RebirthDB is finally born!

I know there is a lot of work ahead but I wanted to ask if any milestone or roadmap of important features will be released?

I have no idea if the following was implemented or what is the status right now as I didn't follow for the past few months but I saw a couple of discussions and thought about :

- Better compression for data at rest
- Optimization/performance
- Give the interface a refresh
- Ability to add/configure a node directly in the interface

Having a roadmap will encourage some users and we'll know what to expect in the future. People may adopt the database because they know X feature they need is being worked on or soon will be.

When I think database I think sharding, fast, big data. RebirthDB with it's changefeed is powerful!

Keep going! xx

**Comment by floydkots** [comment]
Thanks @Extarys, we appreciate your kind words and the suggestion. 

We'll consider it and put up the milestones appropriately. We'll also post updates of the progress (as regards the milestones) here.

**Comment by floydkots** [comment]
And, I forgot to mention, we have this [awesome community on spectrum](https://spectrum.chat/rebirthdb), would you please join us?

Most of the communication and planning goes on there.

**Comment by Extarys** [comment]
Hey, thanks @floydkots, I didn't know about spectrum. That is awesome and exactly what I needed.
