### ISSUE TITLE
Fix the repo URL

### ISSUE THREAD

**Issue by dandv** [rethinkdb/rethinkdb_rebirth#29]
![image](https://user-images.githubusercontent.com/33569/44296426-e9aa7000-a273-11e8-9f15-5d0f880d965e.png)

**Comment by floydkots** [comment]
Thanks, that's a nice catch @dandv!

However, seeing that [we are merging back to RethinkDB](https://spectrum.chat/thread/0d28e226-c240-465b-b67c-1b1be2cdb58a), we'll just keep it that way :)
