### ISSUE TITLE
Questions about  Core Developers of original RethinkDB  - are they joining?

### ISSUE THREAD

**Issue by v3ss0n** [rethinkdb/rethinkdb_rebirth#30]
How many core developers of orginal RethinkDB are here? 
Do they aware of this fork , are they contributing?
Srh and Atnnn was active before , are they still working on old rethinkdb repo?
His work on performance improvement of RethinkDB is huge so is that included here?
https://github.com/srh/rethinkdb/releases/tag/v2.3.5-srh-extra
http://samuelhughes.com/rethinkdb/index.html

**Comment by floydkots** [comment]
Hey @v3ss0n, to answer your questions: 
> How many core developers of orginal RethinkDB are here?

None

> Do they aware of this fork , are they contributing?

We believe they are aware of the fork. They may not have made direct contributions yet, but their contributions to the upstream RethinkDB repo are very valuable. Not to mention the cogent issues that they have brought to our attention.

> Srh and Atnnn was active before , are they still working on old rethinkdb repo?

We may not have exact information as regarding this, but we've seen some work on the old repo from time to time.

> His work on performance improvement of RethinkDB is huge so is that included here?

Once [we merge back](https://spectrum.chat/thread/0d28e226-c240-465b-b67c-1b1be2cdb58a), we will most likely include it.

Should you have further questions of a similar nature, please do not hesitate to reach out to us at [Spectrum](https://spectrum.chat/rethinkdb). And do join [our community there](https://spectrum.chat/rethinkdb), in case you haven't already :)
