### ISSUE TITLE
Add clustering keys for efficient query on time series data

### ISSUE THREAD

**Issue by yjiangnan** [rethinkdb/rethinkdb_rebirth#32]
Rethinkdb is great for real "time" data. Ironically, its query performance on time series data is poor, especially when the table contains millions of documents. The major problem is that every document is independently treated by its primary key. Any range query would look across the whole database and retrieve documents one by one. 

However, in other databases such as Cassandra and YugaByte, there is a concept of compound key consisting of partition keys and clustering keys. Partition keys determine the storage region of the data while clustering keys determine the order of the documents. Documents with the same partition keys are saved together and sorted according to the clustering keys. This offers a great performance advantage for continuous data such as time series data, both in terms of storage space and query speed. It also allows to combine similar tables and reduce the number of tables and overhead. For example, for stock market data, it is more efficient to store data for each stock in a separate table but that would result in hundreds of tables. However, in YugaByte, one can simply do it in a single table and use the stock name as the partition key and time as the clustering key.

Could the same data structure be implemented in RebirthDB? It would be very attractive if RebirthDB could have this feature.

**Comment by floydkots** [comment]
Hi @yjiangnan. Thank you for this feature request.

While we can guarantee that we will deliberate on your request, we can't guarantee the outcome of that process at this point. 

Thank you for your patience thus far. We will update this issue as soon as we have something more concrete.

**Comment by thelinuxlich** [comment]
Hello @yjiangnan , we actually have plans for columnar storage in 2.5 or 2.6, but it will depend on some sponsorship dedicated to one of the core developers deeply involved with this feature.
