### ISSUE TITLE
Ubuntu Repository is not signed

### ISSUE THREAD

**Issue by j4m3z0r** [rethinkdb/rethinkdb_rebirth#33]
Hi guys, I just tried to install your packages following the instructions in your quick start and I get the following error when I run `apt update`:

```
E: The repository 'https://dl.bintray.com/rebirthdb/apt bionic Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I added the key using apt-key, but it doesn't seem to make any difference.

**Comment by j4m3z0r** [comment]
Sorry, forgot to mention: Ubuntu 18.04 on x64.

**Comment by okanbasoglu** [comment]
Having the same issue here. 

Ubuntu 18.04 on x64 
```
E: The repository 'https://dl.bintray.com/rebirthdb/apt bionic Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Hope someone takes care of this.

**Comment by floydkots** [comment]
Hey, @j4m3z0r and @okanbasoglu, thank you for raising this issue. We are sorry about the trouble you've had there.

At this point, we haven't had an official release. So, no packages have been deployed to the [`rebirthdb` debian repository](https://bintray.com/rebirthdb/apt/rebirthdb). 

However, we've had a pre-release and built some test packages which can be found in the [`rebirthdb-dev` debian repository](https://bintray.com/rebirthdb/apt/rebirthdb-dev).

If you would like to simply explore and get a feel of RebirthDB, then I would suggest (a temporary and  rather hacky way of) installing it from the dev repository i.e.
```bash
$ source /etc/lsb-release && echo "deb https://dl.bintray.com/rebirthdb-dev/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rebirthdb.list

$ wget -qO- https://dl.bintray.com/rebirthdb/keys/pubkey.gpg | sudo apt-key add -

$ sudo apt-get update

$ sudo apt-get install rebirthdb
```

However, as you may have noticed already, [we are merging back to RethinkDB](https://spectrum.chat/thread/0d28e226-c240-465b-b67c-1b1be2cdb58a). Consequently, you might want to wait until the merges and changes stabilise and we go through the much awaited **v2.4** release, which will be soon :)

Please do not hesitate to reopen this issue should you experience further challenges. Furthermore, kindly consider joining [our awesome community on Spectrum](https://spectrum.chat/rethinkdb) in case you haven't already.

**Comment by FranklinYu** [comment]
Sorry if this is off topic; searching "Bionic" in issue list brings me here.

So after the merge, RethinkDB v2.4 will be available to http://download.rethinkdb.com/apt? Or we should move to Bintray? Currently there is no way to install RethinkDB on Ubuntu Bionic. Not even the dev repository:

```text
Err:11 https://dl.bintray.com/rebirthdb-dev/apt bionic Release
  404  Not Found [IP: 75.126.118.188 443]
```
