### ISSUE TITLE
Can't migrate from rethinkdb data file

### ISSUE THREAD

**Issue by j4m3z0r** [rethinkdb/rethinkdb_rebirth#34]
Worked around the apt issues by installing the .deb file directly, updated my init scripts to point to rebirthdb rather than rethinkdb and restarted. Was expecting that rebirthdb would convert my rethinkdb database over to rebirthdb, however it just created a new one under a `rebirthdb_data` directory. Copying my `rethinkdb_data` directory over this `rebirthdb_data` directory gives me the following error:

```
error: This doesn't appear to be a RethinkDB data file.
```

(ironically, I think the issue is precisely that it *is* a RethinkDB data file).

If there's a migration step I need to do to switch over, I'm happy to do that, but I didn't see any mention of that in your README.

**Comment by asakatida** [comment]
I would expect a backup and restore is the required process. This user story isn't in our tests yet, and there is discussion of a merge back to RethinkDB before release of 2.4. That would make this fall under the old test system.

**Comment by floydkots** [comment]
Hi @j4m3z0r, you might also find [this part of the docs](https://www.rethinkdb.com/docs/migration/) useful for further information. 

We are doing some tidying and re-organisation. Therefore, we'll close this issue.

Should you have further questions on how to go about the backup and restoration (or anything related), please reach out to us at [our awesome community on Spectrum](https://spectrum.chat/rethinkdb).
