### ISSUE TITLE
Stucked on [1/11] BUILD v8_3.30.33.16-patched2

### ISSUE THREAD

**Issue by rutvik106** [rethinkdb/rethinkdb_rebirth#37]
I am on Cent OS 6 (GoDaddy VPS). using Developer Toolset 7. "scl enable devtoolset-7 -- make" gets stuck at: [1/11] BUILD v8_3.30.33.16-patched2. Please help.

**Comment by asakatida** [comment]
v8 code and references were replaced with a lighter weight in process environment. That build line indicates `configure` should be rerun against the latest code.
