### ISSUE TITLE
Query Profiler - Shard Accesses

### ISSUE THREAD

**Issue by AaronTrazona** [rethinkdb/rethinkdb_rebirth#41]
Hi everyone,

I have a little question, I hope someone can enlighten me 

I doing some  optimization with my queries using the query profiler 
to determine the expensive queries. In the Query Profiler, I notice
"shard accesses" so wondering what should be ideal number for "shard accesses".

Here's the sample query profiler 
![05-10-2018 13-02-49](https://user-images.githubusercontent.com/1627816/46516909-0855dc00-c89f-11e8-8164-2d24dee19e0e.jpg)
![05-10-2018 13-02-30](https://user-images.githubusercontent.com/1627816/46516911-08ee7280-c89f-11e8-8550-67420a089bc8.jpg)

I don't know if this is the correct assumption for this "more shard being used is better".

Thanks

**Comment by thelinuxlich** [comment]
More shards add more latency, it's difficult to do a rough estimate.
