### ISSUE TITLE
Graphics assets

### ISSUE THREAD

**Issue by Bacto** [rethinkdb/rethinkdb_rebirth#51]
Hi,

I'm very happy to see that something is going on RethinkDB :)

I would like to prepare the future release on our PAAS Stackhero (https://www.stackhero.io).
For that I need the logo but can't find a SVG version.
Is there a way to get it as an SVG file? If so, it could be great to put in with sources.

Thanks,
Adrien

**Comment by thelinuxlich** [comment]
Hi Adrien! We opened a art repository in the organization and now we are waiting the Linux Foundation to send us the art assets. Everything will be there, Stay tuned

**Comment by Bacto** [comment]
Awesome. Thanks for your reply :)
