### ISSUE TITLE
Cannot install RebirthDB

### ISSUE THREAD

**Issue by binaek** [rethinkdb/rethinkdb_rebirth#54]
When I try to install RebirthDB, it spits out an error:

E: The repository 'https://dl.bintray.com/rebirthdb/apt bionic Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Any idea how I can get it working?

I was following the installation instructions given in the ReadMe.md of the *next* branch

**Comment by cfanoulis** [comment]
Can reproduce ubuntu 18.10

**Comment by ouroboroscoding** [comment]
Same problem, when is RethinkDB going to be available for 18.04?

**Comment by cfanoulis** [comment]
can repro on ubuntu 18.04 as well, fix ya stoof

**Comment by factormaarten** [comment]
When is a fix gonna be available? Just to have the full picture:

wget -qO- https://dl.bintray.com/rethinkdb/keys/pubkey.gpg | sudo apt-key add -
gives gpg: no valid OpenPGP data found.

**Comment by atris** [comment]
@floydkots, does this seem related to the recent keybase resets we saw?

**Comment by atris** [comment]
@floydkots, seems related to keybase reset?

**Comment by floydkots** [comment]
@atris, nope, they are not related. We are yet to set up the `rethinkdb` repositories on bintray.

@mpjraaij, as soon as we have a proper release candidate, we'll fix the installation issues and do a release. A lot of the energy currently is going into testing and fixing the current problems.

@binaek89, @ouroboroscoding the instructions in the README were set up in anticipation of a release (of `rebirthdb`) right before we merged back with `rethinkdb`. After the merge, we resolved to fix some thorny issues first before doing the 2.4 release. While there is progress, it's difficult to attach an ETA to it.

**Comment by itsazzad** [comment]
http://download.rethinkdb.com/apt/dists/
No distribution for bionic!
```
E: The repository 'http://download.rethinkdb.com/apt bionic Release' does not have a Release file.
```

**Comment by RobMaple** [comment]
I've been having issues installing on 16.04 and realised it was specifically from following the installation guide on github -- the rethinkdb website instructions work fine. The difference being the github installation tries to download from bintray whereas the the rethinkdb ones come from rethinkdb.com

**Comment by FranklinYu** [comment]
@floydkots Is there anything we can help? Are we having any issue publishing [v2.3.6](https://github.com/rethinkdb/rethinkdb/releases/tag/v2.3.6)?

**Comment by floydkots** [comment]
> @floydkots Is there anything we can help? Are we having any issue publishing [v2.3.6](https://github.com/rethinkdb/rethinkdb/releases/tag/v2.3.6)?

Hi @FranklinYu, please see my response here: https://spectrum.chat/rethinkdb/engineering/package-ubuntu-bionic~aaa7e272-0b6f-4681-8715-158c6d3df894?m=MTU0Nzc0NTAzMzEzOQ==
