### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by ChrisTalman** [rethinkdb/rethinkdb_rebirth#58]
Is there a Discord server for RethinkDB? If not, could we create one?

Discord is used by [a lot of open source projects](https://discordapp.com/open-source) and is really fun and convenient to use.

I'm aware that the project has a Spectrum community. I'm not familiar with that platform, but its structure seems different from Discord. I think that some users might find Discord to be more accessible than Spectrum. In particular, the structure is more accessible to some, and it has mobile apps. Perhaps there's room for both in our community?

**Comment by thelinuxlich** [comment]
We had a internal discussion months ago about that and decided to make Spectrum the sole communication hub as Discord lacks some features desirable for project management/Q&A.
