### ISSUE TITLE
How to update multiple values of a certain type?

### ISSUE THREAD

**Issue by Andre601** [rethinkdb/rethinkdb_rebirth#60]
I want to change some values, that are stored in RethinkDB.
The issue is, that there are multiple entries with different tables and such and I don't really go through each one by one to update the values.
I also only want to change a value, if the old one is a certain one.

**Example**:
I have a table, where (after the ID) three values are stored: message, color and name.
Now I want to update all the values in `color` to `green`, but only if the current value of that entry is `color_green`.
Is there a way, to achieve this (tl;dr a advanced filter and replace-method.)?

**Comment by ChrisTalman** [comment]
If I understand you correctly, this could be achieved using a predicate function. For instance, in JavaScript:

```JavaScript
r
	.table('Messages')
	.filter(message => message('color').eq('color_green'))
	.update('green')
```

There's some examples of this [in the documentation](https://www.rethinkdb.com/api/javascript/filter/#more-complex-predicates). The query language is very powerful for operations like this.

**Comment by Andre601** [comment]
ok. I'll take a look at that.
thanks for the help.
