### ISSUE TITLE
Revoking contributor license from RethinkDB

### ISSUE THREAD

**Issue by atris** [rethinkdb/rethinkdb_rebirth#63]
I would like to revoke the contributor license that I signed for my contributions to RethinkDB, hereby taking back any rights that RethinkDB community has to use my contributions in the codebase. I would request the administrators to please delete all my commits and all my branches, and not use any of my code or ideas embodied in the code in any future or current release

**Comment by thelinuxlich** [comment]
That's pretty vague, unless you pinpoint exactly what needs to be gone, it will remain the same.

**Comment by thelinuxlich** [comment]
Closing in favor of a specific issue.
