### ISSUE TITLE
Node.js driver

### ISSUE THREAD

**Issue by janecek** [rethinkdb/rethinkdb_rebirth#66]
Hi, what is the actual preferred Node.js driver for RethinkDB. Is it rethinkdb-ts, rethinkdb-js or rethinkdbdash?
Thanks

**Comment by vodolaz095** [comment]
in my opinion - http://justonepixel.com/thinky/ based around rethinkdbdash

**Comment by GaikwadPratik** [comment]
Seems like they are saying `rethinkdb-ts`... [source](https://github.com/rethinkdb/rethinkdb-js/issues/19). Can anyone from the developer plz confirm?

**Comment by thelinuxlich** [comment]
we confirm!
