### ISSUE TITLE
Unable to donate $$$!!!

### ISSUE THREAD

**Issue by jasonCodesAway** [rethinkdb/rethinkdb_rebirth#68]
I tried to donate $50 here for this awesome project: https://www.rethinkdb.com/contribute/#donate
However, I get the attached "502 Bad Gateway" error. I tried twice, didn't see anything post to my credit card. 

Thanks for the awesome project! 
<img width="1084" alt="rethinkdb donation 502 bad gateway error" src="https://user-images.githubusercontent.com/14617506/49952549-20af2c00-feca-11e8-82e1-cf05d1a15cb7.png">

**Comment by jasonCodesAway** [comment]
Apparently I didn't wait long enough, the charges both now show as pending. Would be nice to not have this error, but enjoy the extra donation, rethink is worth it!

**Comment by thelinuxlich** [comment]
Jason, we will be setting up a Patreon to fund the continued development of RethinkDB soon...stay tuned for awesome news
