### ISSUE TITLE
Future of RethinkDB

### ISSUE THREAD

**Issue by gustavopch** [rethinkdb/rethinkdb_rebirth#69]
Hi.

Having recently discovered RethinkDB and found it an awesome piece of software that provides a delightful development experience, I'm confused about its future.

Will it be maintained and will new features land? Should people still develop apps for production using it or better move to other databases? Any economic strategy to get enough traction to keep an active development? Anybody planning a new business around it (i.e. DBaaS, BaaS, etc.) to keep it alive? Or will it just slowly die?

**Comment by mwakerman** [comment]
Regrettably, I really don’t think anyone should be starting any new commercial projects with RethinkDB. There are no devs, it’s been 1.5 years since the last release (from memory, the 2.4 release was actually paid for, unsure what happened), there are some plans to move the guts to FoundationDB.

**Comment by thelinuxlich** [comment]
Hi Gustavo. There are plans to open a Patreon and fund the continued development of RethinkDB, as @mwakerman said, with FoundationDB as the well, foundation.
I have a web analytics system using RethinkDB as the primary database FYI.
