### ISSUE TITLE
Just here to say thank you for saving rethinkdb!

### ISSUE THREAD

**Issue by ThatLurker** [rethinkdb/rethinkdb_rebirth#7]
![you-are-awesome-wallpaper](https://user-images.githubusercontent.com/1533244/40919278-b8b33c3a-6811-11e8-88bc-135c28f5262b.jpg)

**Comment by thelinuxlich** [comment]
Thank you too for still believing in our dream!

The community is here, please join: https://spectrum.chat/rebirthdb
