### ISSUE TITLE
Status of this repository?

### ISSUE THREAD

**Issue by eritbh** [rethinkdb/rethinkdb_rebirth#76]
Hi, I'm a bit confused on the difference between this repository and https://github.com/rethinkdb/rethinkdb. I understand that at some point, the original developers of RethinkDB abandoned the project, and this repo was used until community members gained access to the original repository; is this one still used at all? If not, can it be marked as archived to avoid confusion?

**Comment by lavvy** [comment]
There was so much traction and so much hope when it was rebirth .
Ever since it moved back to rethink it died again. 
Wether it was a bait, no one can tell

**Comment by thelinuxlich** [comment]
The intention was to merge some things people did in this branch to the rethinkdb branch. It's here in case someone do this PR, anyway, development is going forward in https://github.com/rethinkdb/rethinkdb

The thing is, unfortunately the project is not interesting enough to attract the kind of developer needed to handle the complex RethinkDB codebase without funding.
