### ISSUE TITLE
Change README.md -- it doesn't make sense

### ISSUE THREAD

**Issue by douglasmccormickjr** [rethinkdb/rethinkdb_rebirth#8]
I'm a bit confused here -- can someone clue me in as to why the front page of RebirthDB is pretty much (or is) an exact copy/replica of RethinkDB?  I know that the transition to a new version/platform is probably going through some growing pains but its going to mislead users (new & veteran) about what's going on here and the somewhat significant departure that's underway.

I'm thrilled that there's new life on this project and I think telling the story around how this effort/thrust is going to spur new dev/features into this system is going to help a great deal in getting people excited and involved.  I'd love to see something like this:

1. **Reborn**: A short welcome to RebirthDB blurb - overview new platform and hit on some highlights
2. **A brief history of RethinkDB**: origin story of the platform, what set it apart
3. **The fork in the road**: explain how the fork happened and what conditions created this event
4. **Latest features**: the latest and greatest improvement of v2.4 and significant upgrades
5. **What to expect now**: a plan for the future and what is going to change in this version
6. **Can you help us?** a list out what's still up in the air in terms of resources and areas that need coverage
7. **Lets Connect**: all the different methods/ways in which the community can collaborate

That's my 2 cents -- I hope this helps a bit

**Comment by mageshkumaar** [comment]
I believe that the contributors are busy with the release of 2.4 which includes some features that was planned for 2.5 and also number of contributors seems to have reduced. Since 2.4 release is nearing, I think README file will also be updated along with it. For more information, you can check out the spectrum [chat](https://spectrum.chat/rebirthdb)

**Comment by thelinuxlich** [comment]
Hi Douglas, you are right, we are doing many things and forgot to change this template yet. As @mageshkumar said, feel free to join us at Spectrum, most of the information in your bullet points are there.

**Comment by asakatida** [comment]
Solved by PR #24. Thanks @floydkots.
